Add Synapse module template
matrix-org/synapse-module-cookiecutter-template pull request #1
Opened 2021-10-13 13:43 UTC by reivilibre

The best description of this template is the [README](https://github.com/matrix-org/synapse-module-cookiecutter-template/tree/e6ccb2507ce77eebe2bda22d2241e4bbb4a53a44).

I have tested it and everything seems to be in order.

(That said, Mypy complains and will continue to do so until we release Synapse 1.46 with https://github.com/matrix-org/synapse/pull/11054).

2021-10-14 13:00 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +            return cattr.structure(config, {{ cookiecutter.module_class_name }}Config)
Why not just `{{ cookiecutter.module_class_name }}Config(**config)`?

2021-10-14 13:00 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +    example_option: bool = False
I'd suggest making it a `pass` rather than trying to make it an example.

2021-10-14 13:03 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +__all__ = ["{{ cookiecutter.module_class_name }}"]
Why not just include the class in this file rather than make a different file for it? Since we already do that for quite a few modules (as most of the time the complexity of a module's code is low enough to allow it).

2021-10-14 13:07 UTC, babolivier commented on README.md
> +    module documentation for more
I don't think this is necessary for a template.

2021-10-14 13:32 UTC, reivilibre commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +__all__ = ["{{ cookiecutter.module_class_name }}"]
It *feels* like bad practice to put anything too beefy in `__init__.py` (circular import issues spring to mind as an actual consequence you usually feel).

I think there's a discontinuity; in single-file projects, beefy `__init__` seems OK but if you stretch into a multiple-file project, I think one generally wants `__init__` to be little more than structure.

It also feels more like a structural file, e.g. `__version__ = ...` and so on. When looking through a project, I tend to glaze over (ignore) `__init__.py` files at first glance. However, maybe that's just me... :innocent: 

I'm curious what other people think?

2021-10-14 13:34 UTC, reivilibre commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +    example_option: bool = False
I feel a bit more strongly about this one; it's fine for people like us who know what `attrs` is but the idea was to provide an example to reduce some of that intimidation factor for other people.

2021-10-14 13:36 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +__all__ = ["{{ cookiecutter.module_class_name }}"]
> I think there's a discontinuity; in single-file projects, beefy `__init__` seems OK but if you stretch into a multiple-file project, I think one generally wants `__init__` to be little more than structure.

I think the same, my point was that in practice we're way more often in the former case than the latter.

2021-10-14 13:37 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +    example_option: bool = False
Fair, then it probably needs a comment to explain what's going on.

2021-10-14 13:39 UTC, babolivier commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +            return cattr.structure(config, {{ cookiecutter.module_class_name }}Config)
Right, this seems like a good enough reason to let it in, I was a bit puzzled because I've never encountered `cattr.structure` in the past. It sounds good to leave this in, maybe with a comment that explains what it does?

2021-10-14 19:17 UTC, callahad commented
> > If we're using this for new projects, should we take the opportunity to move away from legacy imperative setup.py and to a declarative setup.cfg?
> 
> Do you have any articles on the benefits of this? This is the first I've heard setup.py being called legacy.

I've posted a longer discussion [privately](https://element.discourse.team/t/on-setuptools-and-declarative-configuration/73), but the central point is that Setuptools itself wants you to use it declaratively. Its own [quickstart docs](https://setuptools.pypa.io/en/latest/userguide/quickstart.html) default to `setup.cfg` and state:

> To avoid executing arbitrary scripts and boilerplate code, we are transitioning into a full-fledged `setup.cfg` to declare your package information instead of running `setup()`.

2021-10-15 09:04 UTC, erikjohnston commented
Thanks for driving this @reivilibre, and would be a marked improvement on our current ad hoc stuff, and generally seems sane.

One thing that worries me a bit is the maintainability of the architecture: i.e. what happens if we want to change the template (e.g. add a new python version to CI)? Right now we'd have to change the template *and* all existing modules, which is going to lead to drift in how our modules are set up.

I'm not really sure what we can do about that. We could aim to use reusable github pipelines, maybe bundle some of the binaries into a separate dev package that we can pull in and so more easily update? It also makes me more sympathetic to the idea that we should try and be as minimal as possible, e.g. is using `towncrier` giving enough benefit that its worth maintaining *across many modules*?

2021-10-15 09:34 UTC, erikjohnston commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +    pass
For Synapse we just set `__version__` and use that everywhere. I don't think its worth complicating it more than that?

2021-10-15 09:55 UTC, erikjohnston commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +    pass
There is native support for pulling the version out of `__init__.py` in setuptools? So the installed version and `__version__` should never get out of sync. So IMO it really is just: do you declare the version here or in setup.py? The advantage with doing it here is that it will *always* be available, and doesn't require pulling in another dep for <=py3.8

2021-10-15 10:32 UTC, reivilibre commented
I don't think GitHub reusable pipelines are the answer here, because they don't apply to GitLab and also don't apply to local development.

Someone mentioned https://earthly.dev but I'm struggling to get a sense of what it feels like and don't know if that really applies to what we're trying to do.

I wonder if git submodules may be useful for pulling in reusable scaffolding: linter configurations, development scripts, and so on?

It might be useful to have a point-by-point list of what we think is concerning to us from a maintenance point of view, because it's hard to fully appreciate the concerns without some specifics.

The things that come to my mind:

* CI configs are bound to specific Python versions, which we will want to increment (e.g. to follow Synapse's version) as they age
  * yes
* Linters are bound to specific versions
  * Not the best for standardisation but not the end of the world; all the scripts will still work, CI still works, the developer experience is the same.
  * (Mypy might be a bit more of a special case)


I'm noticing quickly that we might end up wanting our own variant of this template because our needs are slightly different to that of a third-party module (mostly around the reusability, but also e.g. `CODEOWNERS` has been mentioned).
If possible, I would like to separate out first-party concerns from this PR into issue #3.

2021-10-15 10:35 UTC, reivilibre commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +    pass
> There is native support for pulling the version out of `__init__.py` in setuptools

Do you have a pointer for that? I'm struggling to find how to do that; Synapse does it by evaluating the Python code in `__init__.py` (I'm happy to change it there to do it using the native support too).

2021-10-15 10:46 UTC, reivilibre commented
So we now have three competing suggestions for doing the package version :P :

* `setuptools_scm` (rely on git tags) (→ `__version__` using `importlib`)
* `setup.cfg` (→ `__version__` using `importlib`)
* `__version__` (→ `setup.cfg` using `version = attr: package.__version__`)
  * slightly undermines the credibility of 'setup.cfg is meant to be *declarative*', but `importlib` is feeling a little bit nastier

Will wait for a round of opinions on that.

2021-10-15 10:58 UTC, reivilibre commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +            return cattr.structure(config, {{ cookiecutter.module_class_name }}Config)
I almost want an excuse to use `ConfigError` in the code so that the import for it isn't redundant (and therefore has to be removed).
Maybe this will be improved in Synapse 1.46, but until then, we don't export the error types so if you use your IDE to import `ConfigError`, you'll import it from its internal path rather than from `synapse.module_api.errors`.

However, it's hard to see an excuse to do so if we're cutting out the example... thoughts? x)

2021-10-15 11:01 UTC, reivilibre commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/module.py
> +    example_option: bool = False
Hm, if we cut out attrs entirely, I'll have to put something worse in its place (like passing back an untyped dict), which is not really what I hoped for in terms of keeping everything mypy-strict.

What do you think would be best?

2021-10-15 11:08 UTC, babolivier commented
> I don't think GitHub reusable pipelines are the answer here, because they don't apply to GitLab and also don't apply to local development.
> 
> Someone mentioned https://earthly.dev but I'm struggling to get a sense of what it feels like and don't know if that really applies to what we're trying to do.
> 
> I wonder if git submodules may be useful for pulling in reusable scaffolding: linter configurations, development scripts, and so on?
> 
> It might be useful to have a point-by-point list of what we think is concerning to us from a maintenance point of view, because it's hard to fully appreciate the concerns without some specifics.
> 
> The things that come to my mind:
> 
>     * CI configs are bound to specific Python versions, which we will want to increment (e.g. to follow Synapse's version) as they age
>       
>       * yes
> 
>     * Linters are bound to specific versions
>       
>       * Not the best for standardisation but not the end of the world; all the scripts will still work, CI still works, the developer experience is the same.
>       * (Mypy might be a bit more of a special case)
> 
> 
> I'm noticing quickly that we might end up wanting our own variant of this template because our needs are slightly different to that of a third-party module (mostly around the reusability, but also e.g. `CODEOWNERS` has been mentioned). If possible, I would like to separate out first-party concerns from this PR into issue #3.

I think an issue with this PR as is is that the template tries to be everything at once and lacks a precise target.

A company writing a Synapse module, us as the Synapse team writing a Synapse module, and a community member writing a Synapse module, are three very different situations that will produce very different code.

I don't think we can realistically make this template appeal to everyone without making it overly complicated and difficult to maintain, and even then it wouldn't be fully possible (because people have e.g. their own preferences for coding style/linting/etc).

Since all of the files in this template seem to be centered around how _we_, as the Synapse team, write modules, why not make this template "the template the Synapse team uses, which might or might not fit your needs"? I think if we want to make it easier for people that aren't us to write a module, the best way is more documentation/tutorials.

2021-10-15 11:21 UTC, reivilibre commented
@babolivier 

After thinking it through, my current plan is to make this PR a baseline template, so that we have *something* for community members. I don't want to make perfect the enemy of the good here.
I personally really appreciate this sort of template when I'm starting using something; it seems only fair to provide something since I've gone to the effort of making this.
(I think I'll probably cut Towncrier and releasing steps out of it; probably also disregard most of the things that don't make sense for someone on the more casual end of things — snipping `__version__` out might be an idea. Will probably leave GitHub/GitLab CI in because those two systems are popular.)
We'll then call that 'done' and branch off to our own variant, which supports us more directly (and I'd like to refer discussion about that to #3).

Other 'companies' (I'm taking this to mean: other maintainers of many modules) will be left on their own, and I don't think we really have much ability to help them out, except for the fact that: the 'community' template will get them going, and they can look at our solutions to things as a reference.

2021-10-15 11:42 UTC, callahad commented on {{ cookiecutter.directory_name }}/{{ cookiecutter.package_name }}/__init__.py
> +    pass
FWIW, [PEP 396: Module Version Numbers](https://www.python.org/dev/peps/pep-0396/), Barry's old attempt at codifying conventions around a `package.__version__` attribute, was finally rejected earlier this year on the basis that:

> The packaging ecosystem has changed significantly in the intervening years since this PEP was first written, and APIs such as importlib.metadata.versions() [11] provide for a much better experience.

In order of preference, I'd probably:

1. Not bother defining a `__version__` attribute here at all.
    Let `setuptools_scm` handle the rest.
2. If we absolutely need the `__version__` attribute for some reason, define it via `importlib.metadata`.
    Let `setuptools_scm` handle the rest.
3. If we absolutely need that attribute and can't use `setuptools_scm`, then hardcode it in `setup.cfg` and define `__version__` with `importlib.metadata`.
4. If we absolutely can't use `importlib.metadata`, then hardcode `__version__` in `__init__.py` and use the `attr: ` trick in `setup.cfg` to reference it.

2021-10-19 22:37 UTC, callahad requested changes
A few nits:

- [x] References setup.py in a  few places, which no longer exists
- [x] Uses Py 3.6 in a bunch of places, but 3.6 is EOL in two months, let's go ahead and nuke it now. Either by using "3.7" specifically, or a generic "3" where applicable.
- [ ] Let's drop the git branch configuration and just use `main`; it's the default for new repos in most tools (GitHub, GitLab, etc.), and the separate `main` + `develop` workflow is unlikely to be necessary in modules.

2021-11-01 09:56 UTC, erikjohnston commented
I think this is a broadly good set of things to include. Thanks!

I'm a bit sad at not having a `__version__`, as it's quite common and is how I always check for the version of a package. I trust that slightly more than `importlib`, since `__version__` is from the *actual* code running, `importlib` will return the wrong version for e.g. a) editable installs and b) packages that have been upgraded since the app was started. (Plus you don't have to worry about figuring out what package a module comes from, i.e. `synapse.__version__` vs `version("matrix-synapse")`). It's not a biggie though.

2021-11-01 11:48 UTC, merged