Make Synapse Core the CODEOWNERS of templated repositories if a `synapse_team` variant is in use.
matrix-org/synapse-module-cookiecutter-template pull request #8
Opened 2021-11-01 14:33 UTC by reivilibre

This adds a `standard` and `synapse_team` variant (presented as a menu).

The Synapse Team variant will include customisations specific to modules maintained by us.

2021-11-02 10:49 UTC, anoadragon453 requested changes
This is a really useful addition! All I have are minor wording suggestions.

2021-11-02 10:49 UTC, anoadragon453 commented on README.md
> +  * `CODEOWNERS` for review requests on Synapse Core Team
```suggestion
  * `CODEOWNERS` for automatic review requests for the Synapse Core Team when a
    pull request is opened
```

2021-11-02 10:49 UTC, anoadragon453 commented on README.md
> +   if the Synapse Team is going to be maintaining this module.
I wonder if "community member" is the right language. I may not consider myself part of the Matrix "community" -- but I do know I'm not part of the Synapse maintenance team.

Perhaps: ?

```suggestion
7. `variant`: Choose whether or not to include the Synapse Team-specific
   customisations; pick `synapse_team` if the module will be maintained
   by the Synapse Team. Otherwise, pick `standard`.
```

2021-11-02 10:49 UTC, anoadragon453 commented on README.md
> +* *Specific to the 'Synapse Team' variant:*
We seem to have a mix of 'Synapse Team' and 'Synapse **Core** Team'.

2021-11-02 14:17 UTC, reivilibre commented on README.md
> +* *Specific to the 'Synapse Team' variant:*
'Synapse Core' refers to the team name on GitHub, but yeah it's not super consistent

2021-11-02 14:20 UTC, reivilibre commented on README.md
> +   if the Synapse Team is going to be maintaining this module.
I'm wondering how this will fit in with customer work;
some customer work is generic enough that we may choose to release it (e.g. https://github.com/matrix-org/synapse-user-restrictions/) at which point it's maintained by the Synapse Team (I guess?).

I don't know about private modules we keep for customers in GitLab; right now they would probably make most sense to be `standard` (since they don't need a CODEOWNERS and they don't need Apache 2.0 licence), but I can see it happening that we make more Element-specific tweaks that *do* make sense for both private and public projects.

For now, though, I think you're right. If we need to make further distinctions down the line, we can cross that bridge then.

2021-11-03 09:35 UTC, anoadragon453 approved these changes
Just minor nits at this point. LGTM otherwise!

2021-11-03 09:35 UTC, anoadragon453 commented on README.md
> +* *Specific to the 'Synapse Team' variant:*
Ah, I see OK. That is a little confusing indeed, but the single quotes do help.

2021-11-03 09:35 UTC, anoadragon453 commented on {{ cookiecutter.directory_name }}/.github/CODEOWNERS
> +# Automatically request reviews from the synapse-core team when a pull request comes in.
An instance of "synapse-core team", whereas elsewhere we have "Synapse Core" team.

Up to you which style you want to use everywhere - either is valid in my eyes. But we should pick one.

2021-11-03 09:35 UTC, anoadragon453 commented on README.md
> +7. `variant`: Choose whether or not to include the Synapse Team-specific
```suggestion
7. `variant`: Choose whether or not to include the 'Synapse Team'-specific
```

2021-11-03 12:00 UTC, merged